chhu_web/djangobb_forum/urls.py
from django.conf.urls import *

from djangobb_forum import settings as forum_settings
from djangobb_forum import views as forum_views
from djangobb_forum.feeds import LastPosts, LastTopics, LastPostsOnForum, \
     LastPostsOnCategory, LastPostsOnTopic
from djangobb_forum.forms import EssentialsProfileForm, \
    PersonalProfileForm, MessagingProfileForm, PersonalityProfileForm, \
    DisplayProfileForm, PrivacyProfileForm, UploadAvatarForm


urlpatterns = patterns('',

    # Forum
    url('^$', forum_views.index, name='index'),
    url('^(?P<forum_id>\d+)/$', forum_views.show_forum, name='forum'),
    url('^moderate/(?P<forum_id>\d+)/$', forum_views.moderate, name='moderate'),
    url('^search/$', forum_views.search, name='search'),
    url('^misc/$', forum_views.misc, name='misc'),

    # User
    url('^user/(?P<username>.*)/upload_avatar/$', forum_views.upload_avatar, {
        'form_class': UploadAvatarForm,
        'template': 'djangobb_forum/upload_avatar.html'
        }, name='forum_profile_upload_avatar'),
    url('^user/(?P<username>.*)/privacy/$', forum_views.user, {
        'section': 'privacy',
        'form_class': PrivacyProfileForm,
        'template': 'djangobb_forum/profile/profile_privacy.html'
        }, name='forum_profile_privacy'),
    url('^user/(?P<username>.*)/display/$', forum_views.user, {
        'section': 'display',
        'form_class': DisplayProfileForm,
        'template': 'djangobb_forum/profile/profile_display.html'
        }, name='forum_profile_display'),
    url('^user/(?P<username>.*)/personality/$', forum_views.user, {
        'section': 'personality',
        'form_class': PersonalityProfileForm,
        'template': 'djangobb_forum/profile/profile_personality.html'
        }, name='forum_profile_personality'),
    url('^user/(?P<username>.*)/messaging/$', forum_views.user, {
        'section': 'messaging',
        'form_class': MessagingProfileForm,
        'template': 'djangobb_forum/profile/profile_messaging.html'
        }, name='forum_profile_messaging'),
    url('^user/(?P<username>.*)/personal/$', forum_views.user, {
        'section': 'personal',
        'form_class': PersonalProfileForm,
        'template': 'djangobb_forum/profile/profile_personal.html'
        }, name='forum_profile_personal'),
    url('^user/(?P<username>.*)/essentials/$', forum_views.user, name='forum_profile_essentials'),
    url('^user/(?P<username>.*)/$', forum_views.user, name='forum_profile'),
    url('^users/$', forum_views.users, name='forum_users'),

    # Topic
    url('^topic/(?P<topic_id>\d+)/$', forum_views.show_topic, name='topic'),
    url('^(?P<forum_id>\d+)/topic/add/$', forum_views.add_topic, name='add_topic'),
    url('^topic/(?P<topic_id>\d+)/delete_posts/$', forum_views.delete_posts, name='delete_posts'),
    url('^topic/move/$', forum_views.move_topic, name='move_topic'),
    url('^topic/(?P<topic_id>\d+)/stick_unstick/(?P<action>[s|u])/$', forum_views.stick_unstick_topic, name='stick_unstick_topic'),
    url('^topic/(?P<topic_id>\d+)/open_close/(?P<action>[c|o])/$', forum_views.open_close_topic, name='open_close_topic'),

    # Post
    url('^post/(?P<post_id>\d+)/$', forum_views.show_post, name='post'),
    url('^post/(?P<post_id>\d+)/edit/$', forum_views.edit_post, name='edit_post'),
    url('^post/(?P<post_id>\d+)/delete/$', forum_views.delete_post, name='delete_post'),
    # Post preview
    url(r'^preview/$', forum_views.post_preview, name='post_preview'),

    # Subscription
    url('^subscription/topic/(?P<topic_id>\d+)/delete/$', forum_views.delete_subscription, name='forum_delete_subscription'),
    url('^subscription/topic/(?P<topic_id>\d+)/add/$', forum_views.add_subscription, name='forum_add_subscription'),

    # Feeds
    url(r'^feeds/posts/$', LastPosts(), name='forum_posts_feed'),
    url(r'^feeds/topics/$', LastTopics(), name='forum_topics_feed'),
    url(r'^feeds/topic/(?P<topic_id>\d+)/$', LastPostsOnTopic(), name='forum_topic_feed'),
    url(r'^feeds/forum/(?P<forum_id>\d+)/$', LastPostsOnForum(), name='forum_forum_feed'),
    url(r'^feeds/category/(?P<category_id>\d+)/$', LastPostsOnCategory(), name='forum_category_feed'),
)

### EXTENSIONS ###

# LOFI Extension
if (forum_settings.LOFI_SUPPORT):
    urlpatterns += patterns('',
        url('^lofi/$', forum_views.index, {'full':False}, name='lofi_index'),
        url('^(?P<forum_id>\d+)/lofi/$', forum_views.show_forum, {'full':False}, name='lofi_forum'),
        url('^topic/(?P<topic_id>\d+)/lofi/$', forum_views.show_topic, {'full':False}, name='lofi_topic'),
    )

# REPUTATION Extension
if (forum_settings.REPUTATION_SUPPORT):
    urlpatterns += patterns('',
        url('^reputation/(?P<username>.*)/$', forum_views.reputation, name='reputation'),
    )

# ATTACHMENT Extension
if (forum_settings.ATTACHMENT_SUPPORT):
    urlpatterns += patterns('',
        url('^attachment/(?P<hash>\w+)/$', forum_views.show_attachment, name='forum_attachment'),
    )

chhu_web/urls.py
from django.conf.urls import *
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static

from djangobb_forum import settings as forum_settings
from djangobb_forum.sitemap import SitemapForum, SitemapTopic


sitemaps = {
    'forum': SitemapForum,
    'topic': SitemapTopic,
}

urlpatterns = patterns('',
    # Website
    url(r'^$', include('website.urls')),
    url(r'^price/', 'website.views.price_view'),
    url(r'^about/', 'website.views.about_view'),
    url(r'^contact/', 'website.views.contact_view'),
    url(r'^services/', 'website.views.services_view'),

    # Admin
    url(r'^admin/', include(admin.site.urls)),

    # Sitemap
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),

    # Apps
    url(r'^forum/account/', include('allauth.urls')),
    url(r'^forum/', include('djangobb_forum.urls', namespace='djangobb')),

)

# PM Extension
if (forum_settings.PM_SUPPORT):
    urlpatterns += patterns('',
        url(r'^forum/pm/', include('django_messages.urls')),
   )

if (settings.DEBUG):
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chhu_web/djangobb_forum/views.py
# coding: utf-8
from __future__ import unicode_literals

import math
from datetime import timedelta
from django.utils import timezone

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.contrib.sites.models import Site
from django.core.cache import cache
from django.core.exceptions import SuspiciousOperation, PermissionDenied
from django.core.urlresolvers import reverse
from django.db import transaction
from django.db.models import Q, F
from django.http import Http404, HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import get_object_or_404, render
from django.utils.encoding import smart_str
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings

from haystack.query import SearchQuerySet, SQ

from djangobb_forum import settings as forum_settings
from djangobb_forum.forms import AddPostForm, EditPostForm, UserSearchForm, \
    PostSearchForm, ReputationForm, MailToForm, EssentialsProfileForm, \
    VotePollForm, ReportForm, VotePollForm, PollForm
from djangobb_forum.models import Category, Forum, Topic, Post, Reputation, \
    Attachment, PostTracking
from djangobb_forum.templatetags import forum_extras
from djangobb_forum.templatetags.forum_extras import forum_moderated_by
from djangobb_forum.util import build_form, paginate, set_language, smiles, convert_text_to_html


User = get_user_model()

def index(request, full=True):
    users_cached = cache.get('djangobb_users_online', {})
    users_online = users_cached and User.objects.filter(id__in=users_cached.keys()) or []
    guests_cached = cache.get('djangobb_guests_online', {})
    guest_count = len(guests_cached)
    users_count = len(users_online)

    _forums = Forum.objects.all()
    user = request.user
    if not user.is_superuser:
        user_groups = user.groups.all() or [] # need 'or []' for anonymous user otherwise: 'EmptyManager' object is not iterable
        _forums = _forums.filter(Q(category__groups__in=user_groups) | Q(category__groups__isnull=True))

    _forums = _forums.select_related('last_post__topic', 'last_post__user', 'category')

    cats = {}
    forums = {}
    for forum in _forums:
        cat = cats.setdefault(forum.category.id,
            {'id': forum.category.id, 'cat': forum.category, 'forums': []})
        cat['forums'].append(forum)
        forums[forum.id] = forum

    cmpkey = lambda x: x['cat'].position
    cats = sorted(cats.values(), key=cmpkey)

    to_return = {'cats': cats,
                'posts': Post.objects.count(),
                'topics': Topic.objects.count(),
                'users': User.objects.count(),
                'users_online': users_online,
                'online_count': users_count,
                'guest_count': guest_count,
                'last_user': User.objects.latest('date_joined'),
                }
    if full:
        return render(request, 'djangobb_forum/index.html', to_return)
    else:
        return render(request, 'djangobb_forum/lofi/index.html', to_return)


@transaction.atomic
def moderate(request, forum_id):
    forum = get_object_or_404(Forum, pk=forum_id)
    topics = forum.topics.order_by('-sticky', '-updated').select_related()
    if request.user.is_superuser or request.user in forum.moderators.all():
        topic_ids = request.POST.getlist('topic_id')
        if 'move_topics' in request.POST:
            return render(request, 'djangobb_forum/move_topic.html', {
                'categories': Category.objects.all(),
                'topic_ids': topic_ids,
                'exclude_forum': forum,
            })
        elif 'delete_topics' in request.POST:
            for topic_id in topic_ids:
                topic = get_object_or_404(Topic, pk=topic_id)
                topic.delete()
            messages.success(request, _("Topics deleted"))
            return HttpResponseRedirect(reverse('djangobb:index'))
        elif 'open_topics' in request.POST:
            for topic_id in topic_ids:
                open_close_topic(request, topic_id, 'o')
            messages.success(request, _("Topics opened"))
            return HttpResponseRedirect(reverse('djangobb:index'))
        elif 'close_topics' in request.POST:
            for topic_id in topic_ids:
                open_close_topic(request, topic_id, 'c')
            messages.success(request, _("Topics closed"))
            return HttpResponseRedirect(reverse('djangobb:index'))

        return render(request, 'djangobb_forum/moderate.html', {'forum': forum,
                'topics': topics,
                #'sticky_topics': forum.topics.filter(sticky=True),
                'posts': forum.posts.count(),
                })
    else:
        raise Http404


def search(request):
    # TODO: used forms in every search type

    def _render_search_form(form=None):
        return render(request, 'djangobb_forum/search_form.html', {'categories': Category.objects.all(),
                'form': form,
                })

    if not 'action' in request.GET:
        return _render_search_form(form=PostSearchForm())

    if request.GET.get("show_as") == "posts":
        show_as_posts = True
        template_name = 'djangobb_forum/search_posts.html'
    else:
        show_as_posts = False
        template_name = 'djangobb_forum/search_topics.html'

    context = {}

    # Create 'user viewable' pre-filtered topics/posts querysets
    viewable_category = Category.objects.all()
    topics = Topic.objects.all().order_by("-last_post__created")
    posts = Post.objects.all().order_by('-created')
    user = request.user
    if not user.is_superuser:
        user_groups = user.groups.all() or [] # need 'or []' for anonymous user otherwise: 'EmptyManager' object is not iterable
        viewable_category = viewable_category.filter(Q(groups__in=user_groups) | Q(groups__isnull=True))

        topics = Topic.objects.filter(forum__category__in=viewable_category)
        posts = Post.objects.filter(topic__forum__category__in=viewable_category)

    base_url = None
    _generic_context = True

    action = request.GET['action']
    if action == 'show_24h':
        date = timezone.now() - timedelta(days=1)
        if show_as_posts:
            context["posts"] = posts.filter(Q(created__gte=date) | Q(updated__gte=date))
        else:
            context["topics"] = topics.filter(Q(last_post__created__gte=date) | Q(last_post__updated__gte=date))
        _generic_context = False
    elif action == 'show_new':
        if not user.is_authenticated():
            raise Http404("Search 'show_new' not available for anonymous user.")
        try:
            last_read = PostTracking.objects.get(user=user).last_read
        except PostTracking.DoesNotExist:
            last_read = None

        if last_read:
            if show_as_posts:
                context["posts"] = posts.filter(Q(created__gte=last_read) | Q(updated__gte=last_read))
            else:
                context["topics"] = topics.filter(Q(last_post__created__gte=last_read) | Q(last_post__updated__gte=last_read))
            _generic_context = False
        else:
            #searching more than forum_settings.SEARCH_PAGE_SIZE in this way - not good idea :]
            topics_id = [topic.id for topic in topics[:forum_settings.SEARCH_PAGE_SIZE] if forum_extras.has_unreads(topic, user)]
            topics = Topic.objects.filter(id__in=topics_id) # to create QuerySet

    elif action == 'show_unanswered':
        topics = topics.filter(post_count=1)
    elif action == 'show_subscriptions':
        topics = topics.filter(subscribers__id=user.id)
    elif action == 'show_user':
        # Show all posts from user or topics started by user
        if not user.is_authenticated():
            raise Http404("Search 'show_user' not available for anonymous user.")

        user_id = request.GET.get("user_id", user.id)
        try:
            user_id = int(user_id)
        except ValueError:
            raise SuspiciousOperation()

        if user_id != user.id:
            try:
                search_user = User.objects.get(id=user_id)
            except User.DoesNotExist:
                messages.error(request, _("Error: User unknown!"))
                return HttpResponseRedirect(request.path)
            messages.info(request, _("Filter by user '%(username)s'.") % {'username': search_user.username})

        if show_as_posts:
            posts = posts.filter(user__id=user_id)
        else:
            # show as topic
            topics = topics.filter(posts__user__id=user_id).order_by("-last_post__created").distinct()

        base_url = "?action=show_user&user_id=%s&show_as=" % user_id
    elif action == 'search':
        form = PostSearchForm(request.GET)
        if not form.is_valid():
            return _render_search_form(form)

        keywords = form.cleaned_data['keywords']
        author = form.cleaned_data['author']
        forum = form.cleaned_data['forum']
        search_in = form.cleaned_data['search_in']
        sort_by = form.cleaned_data['sort_by']
        sort_dir = form.cleaned_data['sort_dir']

        query = SearchQuerySet().models(Post)

        if author:
            query = query.filter(author__username=author)

        if forum != '0':
            query = query.filter(forum__id=forum)

        if keywords:
            if search_in == 'all':
                query = query.filter(SQ(topic=keywords) | SQ(text=keywords))
            elif search_in == 'message':
                query = query.filter(text=keywords)
            elif search_in == 'topic':
                query = query.filter(topic=keywords)

        order = {'0': 'created',
                 '1': 'author',
                 '2': 'topic',
                 '3': 'forum'}.get(sort_by, 'created')
        if sort_dir == 'DESC':
            order = '-' + order

        posts = query.order_by(order)

chhu_web/djangobb_forum/templates/djangobb_forum/profile/profile_admin.html
{% extends 'djangobb_forum/base.html' %}
{% load forum_extras %}
{% load i18n %}

{% block content %}
<div id="profile" class="block2col">
	{% include 'djangobb_forum/profile/profile_menu.html' %}
	<div class="blockform">
		<h2><span>{{ profile.username }} - {% trans "Administration" %}</span></h2>
		<div class="box">
			<form id="profile7" method="post">
				{% csrf_token %}
				<div class="inform">

					<fieldset>
						<legend>{% trans "Delete (administrators only) or ban user" %}</legend>
						<div class="infldset">
							<input name="delete_user" value="{% trans "Delete user" %}" type="submit">&nbsp;&nbsp;<input name="ban" value="{% trans "Ban user" %}" type="submit">
						</div>
					</fieldset>
				</div>

				<div class="inform">
					<fieldset>
						<legend>{% trans "Set moderator access" %}</legend>
						<div class="infldset">
							<p>{% trans "Choose what forums this user should be allowed to moderate. Note: This only applies to moderators. Administrators always have full permissions in all forums." %}</p>
							<div class="conl">
								{{ form.forums }}
							</div>
							<br class="clearb"><input name="update_forums" value="{% trans "Update forums" %}" type="submit">
						</div>
					</fieldset>

				</div>
			</form>
		</div>
	</div>
	<div class="clearer"></div>
</div>
{% endblock %}

{% block controls %}
{% endblock %}

chhu_web/djangobb_forum/templates/djangobb_forum/profile/profile_display.html
{% extends 'djangobb_forum/base.html' %}
{% load forum_extras %}
{% load i18n %}

{% block content %}
<div id="profile" class="block2col">
	{% include 'djangobb_forum/profile/profile_menu.html' %}
	<div class="blockform">
		<h2><span>{{ profile.username }} - {% trans "Display" %}</span></h2>
		<div class="box">
			<form id="profile5" method="post">
				{% csrf_token %}
				<div class="inform">
					<fieldset>
						<legend>{% trans "Select your preferred style" %}</legend>
						<div class="infldset">
							{{ form.theme.errors }}
							<label>{% trans "If you like you can use a different visual style for this forum." %}<br>
							{{ form.theme }}
							<br></label>
						</div>
					</fieldset>
					<br/>
					<fieldset>
						<legend>{% trans "Markup" %}</legend>
						<div class="infldset">
							<div class="rbox">
							{{ form.markup.errors }}
							<label>{{ form.markup }}<br></label>
							</div>
						</div>
					</fieldset>
					<br/>
					<fieldset>
						<legend>{% trans "Post display legend" %}</legend>
						<div class="infldset">
							<p>{% trans "Post display info" %}</p>
							<div class="rbox">
							{{ form.show_smilies.errors }}
							<label>{{ form.show_smilies }}{% trans "Show smilies" %}<br></label>
							</div>
						</div>
					</fieldset>
				</div>
				<p><input name="update" value="{% trans "Submit" %}" type="submit">{% trans "When you update your profile, you will be redirected back to this page." %}</p>
			</form>
		</div>
	</div>
	<div class="clearer"></div>
</div>
{% endblock %}

{% block controls %}
{% endblock %}

chhu_web/djangobb_forum/templates/djangobb_forum/profile/profile_essentials.html
{% extends 'djangobb_forum/base.html' %}
{% load forum_extras %}
{% load i18n %}

{% block content %}
<div id="profile" class="block2col">
	{% include 'djangobb_forum/profile/profile_menu.html' %}
	<div class="blockform">
		<h2><span>{{ profile.username }} - {% trans "Essentials" %}</span></h2>
		<div class="box">
			<form id="profile1" method="post">
				{% csrf_token %}
				<div class="inform">
					<fieldset>
						<legend>{% trans "Enter your username and password" %}</legend>
						<div class="infldset">
							{{ form.username.errors }}
							<label><strong>{{ form.username.label }}</strong><br>
							{{ form.username }}
							{% if not user.is_superuser %}
								{{ form.fields.username.initial }}
							{% endif %}
							<br></label>
							<p>
							{% if user.is_superuser %}
								<a href="{% url 'admin:auth_user_password_change' profile.id %}">{% trans "Change password" %}</a>
							{% else %}
								<a href="{% url 'account_change_password' %}">{% trans "Change password" %}</a>
							{% endif %}
							</p>
					</div>
					</fieldset>
				</div>
				<div class="inform">
					<fieldset>
						<legend>{% trans "Enter a valid e-mail address" %}</legend>
						<div class="infldset">
							{{ form.email.errors }}
							<label><strong>{{ form.email.label }}</strong><br>
							{{ form.email }}<br></label>
							{% if user.is_superuser %}
								<p><a href="{% url 'djangobb:misc' %}?mail_to={{ profile }}">{% trans "Send e-mail" %}</a></p>
							{% endif %}

						</div>
					</fieldset>
				</div>
                <div class="inform">
                    <fieldset>
                        <legend>{{ form.auto_subscribe.label }}</legend>
                        <div class="infldset">
                            {{ form.auto_subscribe.errors }}
                            {{ form.auto_subscribe }} <label for="id_auto_subscribe">{{ form.auto_subscribe.help_text }}</label>
                        </div>
                    </fieldset>
                </div>
				<div class="inform">
					<fieldset>
						<legend>{% trans "Set your localisation options" %}</legend>
						<div class="infldset">
							{{ form.time_zone.errors }}
							<label>
								{% trans "Timezone: For the forum to display times correctly you must select your local timezone." %}<br>
							<br>
							{{ form.time_zone }}
							</label>
							{{ form.language.errors }}
							<label>
								{% trans "Language: You can choose which language you wish to use to view the forum" %}
							<br>
							{{ form.language }}
							<br></label>
						</div>
					</fieldset>
				</div>
				<div class="inform">

					<fieldset>
						<legend>{% trans "User activity" %}</legend>
						<div class="infldset">
							<p>{% trans "Registered:" %} {{ profile.date_joined|date:"Y-m-d" }}</p>
							<p>{% trans "Last post:" %} {{ profile.forum_profile.last_post }}</p>
							<label>{% trans "Posts:" %} {{ profile.forum_profile.post_count }} -
							<a href="{% url 'djangobb:search' %}?action=show_user&user_id={{ profile.id }}">{% trans "Show all posts" %}</a></p>
							</label>
						</div>
					</fieldset>
				</div>
				<p><input name="update" value="{% trans "Submit" %}" type="submit">{% trans "When you update your profile, you will be redirected back to this page." %}</p>
			</form>
		</div>

	</div>
	<div class="clearer"></div>
</div>
{% endblock %}

{% block controls %}
{% endblock %}

chhu_web/djangobb_forum/templates/djangobb_forum/profile/profile_menu.html
{% load i18n %}
	<div class="blockmenu">
		<h2><span>{% trans "Profile menu" %}</span></h2>
		<div class="box">
			<div class="inbox">
				<ul>
					<li {%if active_menu == "essentials" %}class="isactive"{% endif %}><a href="{% url 'djangobb:forum_profile_essentials' profile %}">{% trans "Essentials" %}</a></li>
					<li {%if active_menu == "personal" %}class="isactive"{% endif %}><a href="{% url 'djangobb:forum_profile_personal' profile %}">{% trans "Personal" %}</a></li>
					<li {%if active_menu == "messaging" %}class="isactive"{% endif %}><a href="{% url 'djangobb:forum_profile_messaging' profile %}">{% trans "Messaging" %}</a></li>
					<li {%if active_menu == "personality" %}class="isactive"{% endif %}><a href="{% url 'djangobb:forum_profile_personality' profile %}">{% trans "Personality" %}</a></li>
					<li {%if active_menu == "display" %}class="isactive"{% endif %}><a href="{% url 'djangobb:forum_profile_display' profile %}">{% trans "Display" %}</a></li>
					<li {%if active_menu == "privacy" %}class="isactive"{% endif %}><a href="{% url 'djangobb:forum_profile_privacy' profile %}">{% trans "Privacy" %}</a></li>
					{# if user.is_superuser #}
					<!--li {% if active_menu == "admin" %}class="isactive"{% endif %}><a href="{% url 'djangobb:forum_profile' profile %}?section=admin">{% trans "Administration" %}</a></li-->
					{# endif #}

				</ul>
			</div>
		</div>
	</div>

chhu_web/djangobb_forum/templates/djangobb_forum/profile/profile_messaging.html
{% extends 'djangobb_forum/base.html' %}
{% load forum_extras %}
{% load i18n %}

{% block content %}
<div id="profile" class="block2col">
	{% include 'djangobb_forum/profile/profile_menu.html' %}
	<div class="blockform">
		<h2><span>{{ profile.username }} - {% trans "Messaging" %}</span></h2>
		<div class="box">
			<form id="profile3" method="post">
				{% csrf_token %}
				<div class="inform">
					<fieldset>
						<legend>{% trans "Personal" %}</legend>
						<div class="infldset">
							{{ form.jabber.errors }}
							<label>{{ form.jabber.label }}<br>{{ form.jabber }}<br></label>
							{{ form.icq.errors }}
							<label>{{ form.icq.label }}<br>{{ form.icq }}<br></label>
							{{ form.msn.errors }}
							<label>{{ form.msn.label }}<br>{{ form.msn }}<br></label>
							{{ form.aim.errors }}
							<label>{{ form.aim.label }}<br>{{ form.aim }}<br></label>
							{{ form.yahoo.errors }}
							<label>{{ form.yahoo.label }}<br>{{ form.yahoo }}<br></label>
						</div>
					</fieldset>
				</div>
				<p><input name="update" value="{% trans "Submit" %}" type="submit">{% trans "When you update your profile, you will be redirected back to this page." %}</p>
			</form>

		</div>
	</div>
	<div class="clearer"></div>
</div>
{% endblock %}

{% block controls %}
{% endblock %}

chhu_web/djangobb_forum/templates/djangobb_forum/profile/profile_personality.html
{% extends 'djangobb_forum/base.html' %}
{% load forum_extras %}
{% load i18n %}

{% block content %}
<div id="profile" class="block2col">
	{% include 'djangobb_forum/profile/profile_menu.html' %}
	<div class="blockform">
		<h2><span>{{ profile.username }} - {% trans "Personality" %}</span></h2>
		<div class="box">
			<form id="profile4" method="post">
				{% csrf_token %}
				<div class="inform">
					<fieldset id="profileavatar">
						<legend>{% trans "Set your avatar display options" %}</legend>
						<div class="infldset">
							{{ profile.forum_profile.avatar.errors }}
							{% if profile.forum_profile.avatar %}
								<img src="{{ profile.forum_profile.avatar.url }}" />
							{% endif %}
							<p>{% trans "An avatar is a small image that will be displayed with all your posts. You can upload an avatar by clicking the link below. The checkbox 'Use avatar' below must be checked in order for the avatar to be visible in your posts." %}</p>
							<div class="rbox">
								{{ form.show_avatar.errors }}
								<label>{{ form.show_avatar }}{% trans "Use avatar." %}<br></label>
							</div>
							<p class="clearb"><a href="{% url 'djangobb:forum_profile_upload_avatar' profile.username %}">{% trans "Upload avatar" %}</a></p>
						</div>
					</fieldset>
				</div>
				<div class="inform">
					<fieldset>
						<legend>{% trans "Compose your signature" %}</legend>
						<div class="infldset">
							{{ form.signature.errors }}
							<p>{% trans "A signature is a small piece of text that is attached to your posts. In it, you can enter just about anything you like. Perhaps you would like to enter your favourite quote or your star sign. It's up to you! In your signature you can use BBCode if it is allowed in this particular forum. You can see the features that are allowed/enabled listed below whenever you edit your signature." %}</p>
							<div class="txtarea">
								<label><br>
								{{ form.signature }}
								<br></label>
							</div>
							{% if profile.forum_profile.signature_html %}
								<p>{{ profile.forum_profile.signature_html|safe }}</p>
							{% else %}
								<p>{% trans "No signature currently stored in profile." %}</p>
							{% endif %}
						</div>
					</fieldset>
				</div>
				<p><input name="update" value="{% trans "Submit" %}" type="submit">{% trans "When you update your profile, you will be redirected back to this page." %}</p>
			</form>
		</div>
	</div>
	<div class="clearer"></div>
</div>
{% endblock %}

{% block controls %}
{% endblock %}